config/routes.rb
Rails.application.routes.draw do

	namespace :admin do
		resources :offer_types
		resources :price_types
		resources :metro_lines
		resources :okrugs
		resources :metro_stations
		resources :facility_types
		resources :regions
		resources :buildings
		resources :floors
		resources :facilities
		resources :offers
		resources :building_types
		delete 'facility_file', to: 'facilities#destroy_file', as: :destroy_file
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
	belongs_to :gallery
	has_and_belongs_to_many :metro_stations
	belongs_to :okrug
	belongs_to :user
	belongs_to :region
	belongs_to :facility_type
	has_many :building
	has_many :offers

	enum level: ['1', '2', '3', '4', '5', '6']

	validates :name, :gallery, :adress, :square_gla, :square, :facility_type, :user,  presence: true

  mount_uploaders :files, FileUploader

	with_options prefix: true, allow_nil: false do
    delegate :name,         to: :facility_type
  end

  geocoded_by :adress

  after_validation :geocode

  before_destroy :clear_stations

  def key_image
    gallery.gallery_attachments.order(:sort).first.image || false
	end

  def clear_stations
		metro_stations.clear
	end
end

app/models/facility_type.rb
class FacilityType < ApplicationRecord
	belongs_to :building
	has_many :facility
	has_many :offer
  belongs_to :seo_field

	validates :name,  presence: true
end

app/controllers/admin/facilities_controller.rb
module Admin
  class FacilitiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Facility.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Facility.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def destroy_file
      facility = Facility.find(params[:facility_id])
      index = params[:index].to_i

      remain_files = facility.files
      deleted_file = remain_files.delete_at(index)
      deleted_file.try(:remove!)

      if remain_files.empty?
        facility.remove_files!
      else
        facility.files = remain_files
      end

      facility.save
      redirect_to edit_admin_facility_path(facility)
    end
  end
end

app/views/admin/facilities/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form", :html => {:multipart => true} }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :name %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field-unit field-unit--has-many">
    <div class="field-unit__label">
      <%= f.label :gallery_id %>
    </div>
    <div class="field-unit__field">
      <%= f.select :gallery_id, options_from_collection_for_select(Gallery.all, :id, :name, page.resource.gallery_id.to_s ), {include_blank: true}, class: 'form-control' %>
    </div>
  </div>
  
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :adress %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :adress, class: 'form-control address' %>
    </div>
  </div>

  <div class="field-unit field-unit--has-many">
    <div class="field-unit__label">
      <%= f.label :files %>
    </div>
    <div class="field-unit__field">
      <%= f.file_field :files, multiple: true, class: 'form-control' %>
    </div>
    <br>
  </div>
  <div style="margin-left: 11%;">
    <% page.resource.files.each_with_index do |file, index| %>
      <div>
        <%= link_to "#{file.file.original_filename}", file.url, { target: "_blank", class: "btn waves-effect white-text" } %>
        <%= link_to admin_destroy_file_path(facility_id: page.resource, index: index), :method => :delete, class: "destroy-link", data: { confirm: "Are you sure you want to delete this file?" } do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
        <%end%>
      </div>
    <% end %>
  </div>

  <table  class="inform" border="0" cellpadding="1" cellspacing="1">
    <tbody>
      <tbody>
          <tr>
            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :square_gla %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--number">
                <%= f.number_field :square_gla, class: 'form-control' %>
              </div>
            </td>

            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :square %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--number">
                <%= f.number_field :square, class: 'form-control' %>
              </div>
            </td>
          </tr>

          <tr>
            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :region_id %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :region_id, options_from_collection_for_select(Region.all, :id, :name, page.resource.region_id.to_s ), {include_blank: true}, class: 'form-control' %>
                </div>
            </td>

            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :metro_station_ids %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :metro_station_ids, options_from_collection_for_select(MetroStation.all, :id, :name, page.resource.metro_stations.map(&:id) ), {}, :multiple => true, class: 'form-control selectized' %>
              </div>
            </td>
          </tr>

          <tr>
            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :okrug_id %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :okrug_id, options_from_collection_for_select(Okrug.all, :id, :name, page.resource.okrug_id.to_s ), {include_blank: true}, class: 'form-control' %>
              </div>
            </td>

            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :published_at %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--date-picker">
                <%= f.date_field :published_at, class: 'date_picker flatpickr-input' %>
              </div>
            </td>
          </tr>

          <tr>
            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :user_id %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :fio, page.resource.user_id.to_s ), {include_blank: true}, class: 'form-control' %>
              </div>
            </td>

            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :facility_type_id %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :facility_type_id, options_from_collection_for_select(FacilityType.all, :id, :name, page.resource.facility_type_id.to_s ), {include_blank: true}, class: 'form-control' %>
              </div>
            </td>
          </tr>
          <tr>
            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :level %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :level, Facility.levels.keys.map {|key| [I18n.t("activerecord.attributes.facility.levels.#{key}"), key]}, {include_blank: true}, class: 'form-control' %>
              </div>
            </td>

            <td class="td-label">
              <div class="field-unit__label">
                <%= f.label :offer_id %>
              </div>
            </td>
            <td class="td-field">
              <div class="field-unit__field field-unit--has-many">
                <%= f.select :offer_ids, options_from_collection_for_select(Offer.all, :id, :name, page.resource.offer_id.to_s ), {include_blank: true}, :multiple => true, class: 'form-control' %>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

  <div class="field-unit field-unit--wysiwyg-field">
    <div class="field-unit__label">
      <%= f.label :description %>
    </div>
    <div class="field-unit__field field-wide">
      <%= f.cktext_area :description, class: 'form-control', rows: 12 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>